config:
  validation: true
  warningsAsErrors: false
  excludes: []

complexity:
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 9
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 20
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerObject: 20
    allowedFunctionsPerEnum: 20
    ignorePrivate: false
    ignoreDeprecated: false
    ignoreOverridden: true
    ignoreAnnotatedFunctions:
      - 'Preview'

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

style:
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: false
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreEnums: true
    ignoreHashCodeFunction: true
    ignoreNamedArgument: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  UnusedPrivateFunction:
    active: true
    allowedNames: '.*Preview$'
